fos_rest:
    param_fetcher_listener: true
    #    allowed_methods_listener:  true
    #    routing_loader:
    #        default_format: json
    #        include_format: false
    view:
        view_response_listener: 'force'
        formats:
            json: true
    #    exception:
    #        codes:
    #            App\Exception\MyException: 403
    #        messages:
    #            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: '^/api/', priorities: [ 'json' ], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
